{{- if and (eq .Values.secretStorage.externalSecrets.enabled false) (not .Values.secretStorage.existingSecret) .Values.secret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "scheduler.fullname" . }}-secrets
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.secret }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- else if and .Values.secretStorage.externalSecrets.enabled (not .Values.secretStorage.existingSecret) }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "scheduler.fullname" . }}-external-secrets
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secretStorage.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStorage.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "scheduler.fullname" . }}-secrets
  data:
    {{- range $key, $value := .Values.secret }}
    {{- if $value }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $.Values.secretStorage.externalSecrets.secretPath }}
        property: {{ $value }}
    {{- end }}
    {{- end }}
{{- end }}
